/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymbolsRouteImport } from './routes/symbols'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as R404RouteImport } from './routes/$404'
import { Route as IndexRouteImport } from './routes/index'

const SymbolsRoute = SymbolsRouteImport.update({
  id: '/symbols',
  path: '/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/runs': typeof RunsRoute
  '/strategies': typeof StrategiesRoute
  '/symbols': typeof SymbolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/runs': typeof RunsRoute
  '/strategies': typeof StrategiesRoute
  '/symbols': typeof SymbolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/runs': typeof RunsRoute
  '/strategies': typeof StrategiesRoute
  '/symbols': typeof SymbolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$404' | '/dashboard' | '/runs' | '/strategies' | '/symbols'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$404' | '/dashboard' | '/runs' | '/strategies' | '/symbols'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/dashboard'
    | '/runs'
    | '/strategies'
    | '/symbols'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRoute
  RunsRoute: typeof RunsRoute
  StrategiesRoute: typeof StrategiesRoute
  SymbolsRoute: typeof SymbolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symbols': {
      id: '/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof SymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRoute,
  RunsRoute: RunsRoute,
  StrategiesRoute: StrategiesRoute,
  SymbolsRoute: SymbolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
